# Generated by Django 4.2.24 on 2025-09-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "permissions": [("can_add_sales", "может проводить продажи")],
                "verbose_name": "Продажа",
            },
        ),
    ]
