# Generated by Django 4.2.24 on 2025-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sale_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "permissions": [
                    ("can_view_sales", "Может просматривать продажи"),
                    ("can_make_sales", "Может проводить продажи"),
                    ("can_delete_sales", "Может удалять продажи"),
                    ("can_edit_sales", "Может редактировать продажи"),
                ],
                "verbose_name": "Продажа",
            },
        ),
    ]
