# Generated by Django 4.2.24 on 2025-09-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sale",
            table=None,
        ),
    ]
