# Generated by Django 4.2.24 on 2025-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_sale_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sale",
            table="Продажи",
        ),
    ]
