# Generated by Django 5.2.4 on 2025-09-12 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания группы"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_groups",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа партий",
                "verbose_name_plural": "Группы партий",
                "db_table": "Группы партий",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена реализации",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "arrival_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата поступления партии"
                    ),
                ),
                (
                    "is_modified",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Отметьте если партия была изменена",
                        verbose_name="Измененная партия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="warehouse.batchgroup",
                        verbose_name="Группа партии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партия товара",
                "verbose_name_plural": "Партии товаров",
                "db_table": "Партии товаров",
                "ordering": ["-arrival_date"],
            },
        ),
    ]
