# Generated by Django 5.2.4 on 2025-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Имя поставщика"
                    ),
                ),
                (
                    "contact_face",
                    models.CharField(max_length=256, verbose_name="Имя менеджера"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=14, verbose_name="Контактный телефон"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="admin@example.com",
                        max_length=256,
                        verbose_name="Контактная электронная почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
            },
        ),
    ]
